<?php
// Configuración de seguridad
require_once __DIR__ . '/app/services/Security.php';

// Iniciar sesión segura y generar token CSRF
Security::start();
$csrf = Security::csrfToken();

// Cargar datos del cliente si está logueado
$clienteData = [
    'tipoId' => '',
    'cedula' => '',
    'nombre' => '',
    'correo' => '',
    'telefono' => ''
];

if (!empty($_SESSION['client_id'])) {
    try {
        $config = require __DIR__ . '/app/config/config.php';
        $pdo = new PDO(
            "mysql:host={$config['db']['mysql']['host']};dbname={$config['db']['mysql']['dbname']};charset={$config['db']['mysql']['charset']}",
            $config['db']['mysql']['user'],
            $config['db']['mysql']['pass'],
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $stmt = $pdo->prepare("SELECT tipo_id, cedula, nombre, correo, telefono FROM clients WHERE id = ?");
        $stmt->execute([$_SESSION['client_id']]);
        $cliente = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($cliente) {
            $clienteData = [
                'tipoId' => $cliente['tipo_id'] ?? 'cedula',
                'cedula' => $cliente['cedula'] ?? '',
                'nombre' => $cliente['nombre'] ?? '',
                'correo' => $cliente['correo'] ?? '',
                'telefono' => $cliente['telefono'] ?? ''
            ];
        }
    } catch (Exception $e) {
        error_log("Error loading client data: " . $e->getMessage());
    }
}
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solicitud Seguro Hogar Comprensivo - INS</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
    * { font-family: 'Inter', sans-serif; }
    .gradient-bg { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
    .step-indicator { transition: all 0.3s ease; }
    .step-indicator.active { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); transform: scale(1.1); }
    .step-indicator.completed { background: #10b981; }
    .form-section { display: none; animation: fadeIn 0.5s ease; }
    .form-section.active { display: block; }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
    .input-field { transition: all 0.3s ease; }
    .input-field:focus { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(102, 126, 234, 0.2); }
    .checkbox-custom { appearance: none; width: 20px; height: 20px; border: 2px solid #d1d5db; border-radius: 4px; cursor: pointer; position: relative; transition: all 0.3s ease; }
    .checkbox-custom:checked { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-color: #667eea; }
    .checkbox-custom:checked::after { content: '✓'; position: absolute; color: white; font-size: 14px; top: 50%; left: 50%; transform: translate(-50%, -50%); }
    .radio-custom { appearance: none; width: 20px; height: 20px; border: 2px solid #d1d5db; border-radius: 50%; cursor: pointer; position: relative; transition: all 0.3s ease; }
    .radio-custom:checked { border-color: #667eea; }
    .radio-custom:checked::after { content: ''; position: absolute; width: 10px; height: 10px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 50%; top: 50%; left: 50%; transform: translate(-50%, -50%); }
    .progress-bar { transition: width 0.5s ease; }
    </style>
</head>
<body class="bg-gray-50">
    <!-- Header -->
    <header class="bg-white shadow-md sticky top-0 z-50">
    <div class="container mx-auto px-4 py-4">
    <div class="flex items-center justify-between">
    <div class="flex items-center space-x-3">
    <div class="w-12 h-12 gradient-bg rounded-lg flex items-center justify-center">
    <i class="fas fa-shield-alt text-white text-xl"></i>
    </div>
    <div>
    <h1 class="text-xl font-bold text-gray-800">Seguro Hogar Comprensivo</h1>
    <p class="text-xs text-gray-500">ASEGURALOCR.COM - Agente: 86611</p>
    </div>
    </div>
    <a href="/index.php" class="text-gray-600 hover:text-purple-600 transition">
    <i class="fas fa-arrow-left mr-2"></i>Volver
    </a>
    </div>
    </div>
    </header>

    <!-- Progress Bar -->
    <div class="bg-white border-b">
    <div class="container mx-auto px-4 py-4">
    <div class="flex justify-between items-center mb-4">
    <div class="flex-1 flex items-center" id="step-indicators">
    <!-- Steps will be generated by JavaScript -->
    </div>
    </div>
    <div class="w-full bg-gray-200 rounded-full h-2">
    <div id="progress-bar" class="progress-bar h-2 rounded-full gradient-bg" style="width: 0%"></div>
    </div>
    <p class="text-center text-sm text-gray-600 mt-2">
    <span id="current-step-text">Paso 1 de 7</span>
    </p>
    </div>
    </div>

    <!-- Main Form Container -->
    <div class="container mx-auto px-4 py-8 max-w-5xl">
    <form id="insurance-form" class="bg-white rounded-2xl shadow-xl p-8" method="post" action="/enviarformularios/hogar_procesar.php" novalidate>
    
    <!-- honeypot -->
    <div style="position:absolute;left:-9999px;opacity:0" aria-hidden="true">
      <label for="website">Website</label>
      <input type="text" name="website" id="website" tabindex="-1" autocomplete="off">
    </div>

    <!-- CSRF -->
    <input type="hidden" name="csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES) ?>">

    <!-- PASO 1: Datos del Tomador/Asegurado -->
    <div class="form-section active" data-step="1">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-user text-purple-600 mr-3"></i>Datos Personales
    </h2>
    <p class="text-gray-600">Información del titular de la póliza</p>
    </div>

    <div class="space-y-6">
    <!-- Tipo de Identificación -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Tipo de Identificación <span class="text-red-500">*</span>
    </label>
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tipoId" value="cedula" class="radio-custom" required <?= $clienteData['tipoId'] === 'cedula' || $clienteData['tipoId'] === '' ? 'checked' : '' ?>>
    <span class="text-sm">Cédula</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tipoId" value="dimex" class="radio-custom" <?= $clienteData['tipoId'] === 'dimex' ? 'checked' : '' ?>>
    <span class="text-sm">DIMEX</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tipoId" value="didi" class="radio-custom" <?= $clienteData['tipoId'] === 'didi' ? 'checked' : '' ?>>
    <span class="text-sm">DIDI</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tipoId" value="pasaporte" class="radio-custom" <?= $clienteData['tipoId'] === 'pasaporte' ? 'checked' : '' ?>>
    <span class="text-sm">Pasaporte</span>
    </label>
    </div>
    </div>

    <!-- Número de Identificación -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Número de Identificación <span class="text-red-500">*</span>
    </label>
    <input type="text" name="numeroId" value="<?= htmlspecialchars($clienteData['cedula']) ?>" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 1-2345-6789" required>
    </div>

    <!-- Nombre Completo -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Nombre Completo <span class="text-red-500">*</span>
    </label>
    <input type="text" name="nombreCompleto" value="<?= htmlspecialchars($clienteData['nombre']) ?>" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Primer Apellido, Segundo Apellido, Nombre" required>
    </div>

    <!-- Ubicación -->
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Provincia <span class="text-red-500">*</span>
    </label>
    <select name="provincia" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    <option value="san-jose">San José</option>
    <option value="alajuela">Alajuela</option>
    <option value="cartago">Cartago</option>
    <option value="heredia">Heredia</option>
    <option value="guanacaste">Guanacaste</option>
    <option value="puntarenas">Puntarenas</option>
    <option value="limon">Limón</option>
    </select>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Cantón <span class="text-red-500">*</span>
    </label>
    <select id="canton" name="canton" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    </select>
    </div>
    </div>

    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Distrito <span class="text-red-500">*</span>
    </label>
    <select id="distrito" name="distrito" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    </select>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    País <span class="text-red-500">*</span>
    </label>
    <input type="text" name="pais" value="Costa Rica" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    </div>
    </div>

    <!-- Dirección Exacta -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Dirección Exacta de Domicilio <span class="text-red-500">*</span>
    </label>
    <textarea name="direccion" rows="3" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ingrese su dirección completa..." required></textarea>
    </div>

    <!-- Teléfonos -->
    <div class="grid md:grid-cols-3 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Teléfono Celular <span class="text-red-500">*</span>
    </label>
    <input type="tel" name="telefonoCelular" value="<?= htmlspecialchars($clienteData['telefono']) ?>" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="8888-8888" required>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Teléfono Domicilio
    </label>
    <input type="tel" name="telefonoDomicilio" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="2222-2222">
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Teléfono Oficina
    </label>
    <input type="tel" name="telefonoOficina" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="2222-2222">
    </div>
    </div>

    <!-- Correo Electrónico -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Correo Electrónico <span class="text-red-500">*</span>
    </label>
    <input type="email" name="correo" value="<?= htmlspecialchars($clienteData['correo']) ?>" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="ejemplo@correo.com" required>
    <p class="text-xs text-gray-500 mt-1">A este correo se enviará la cotización</p>
    </div>
    </div>
    </div>

    <!-- PASO 2: Datos de la Propiedad -->
    <div class="form-section" data-step="2">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-home text-purple-600 mr-3"></i>Datos de la Propiedad
    </h2>
    <p class="text-gray-600">Información del inmueble a asegurar</p>
    </div>

    <div class="space-y-6">
    <!-- Tipo de Propiedad -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Tipo de Propiedad <span class="text-red-500">*</span>
    </label>
    <div class="grid grid-cols-2 gap-4">
    <label class="flex items-center space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="tipoPropiedad" value="casa" class="radio-custom" required>
    <div>
    <div class="font-semibold text-gray-800">Casa de habitación</div>
    <div class="text-xs text-gray-500">Casa independiente</div>
    </div>
    </label>
    <label class="flex items-center space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="tipoPropiedad" value="apartamento" class="radio-custom">
    <div>
    <div class="font-semibold text-gray-800">Apartamento</div>
    <div class="text-xs text-gray-500">En condominio</div>
    </div>
    </label>
    </div>
    </div>

    <!-- Georreferencia -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
    <h3 class="font-semibold text-gray-800 mb-3 flex items-center">
    <i class="fas fa-map-marker-alt text-blue-600 mr-2"></i>Georreferencia <span class="text-red-500 ml-1">*</span>
    </h3>
    <p class="text-xs text-gray-600 mb-3">Use 7 decimales. Ejemplo: 9.9345678, -84.0856789</p>
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Latitud</label>
    <input type="text" name="latitud" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="9.9345678" pattern="^-?\d+\.\d{7}$">
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Longitud</label>
    <input type="text" name="longitud" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="-84.0856789" pattern="^-?\d+\.\d{7}$">
    </div>
    </div>
    </div>

    <!-- Ubicación de la Propiedad -->
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Provincia <span class="text-red-500">*</span>
    </label>
    <select name="provinciaProp" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    <option value="san-jose">San José</option>
    <option value="alajuela">Alajuela</option>
    <option value="cartago">Cartago</option>
    <option value="heredia">Heredia</option>
    <option value="guanacaste">Guanacaste</option>
    <option value="puntarenas">Puntarenas</option>
    <option value="limon">Limón</option>
    </select>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Cantón <span class="text-red-500">*</span>
    </label>
    <select id="cantonProp" name="cantonProp" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    </select>
    </div>
    </div>

    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Distrito <span class="text-red-500">*</span>
    </label>
    <select id="distritoProp" name="distritoProp" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    </select>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    ¿Localizado en esquina? <span class="text-red-500">*</span>
    </label>
    <div class="flex space-x-6 pt-3">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="esquina" value="si" class="radio-custom" required>
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="esquina" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    </div>
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Urbanización, Barrio, Residencial o Condominio
    </label>
    <input type="text" name="urbanizacion" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: Residencial Los Olivos">
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Otras Señas
    </label>
    <textarea name="otrasSenas" rows="2" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Descripción adicional de la ubicación"></textarea>
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Número de Folio Real o Finca
    </label>
    <input type="text" name="folioReal" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 123456">
    </div>
    </div>
    </div>

    <!-- PASO 3: Características de Construcción -->
    <div class="form-section" data-step="3">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-building text-purple-600 mr-3"></i>Características de Construcción
    </h2>
    <p class="text-gray-600">Detalles técnicos de la propiedad</p>
    </div>

    <div class="space-y-6">
    <!-- Año de Construcción -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Rango de Año de Construcción <span class="text-red-500">*</span>
    </label>
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition text-center">
    <input type="radio" name="anoConst" value="antes-1974" class="hidden peer" required>
    <span class="text-sm peer-checked:font-bold">Antes de 1974</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition text-center">
    <input type="radio" name="anoConst" value="1974-1985" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">1974-1985</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition text-center">
    <input type="radio" name="anoConst" value="1986-2001" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">1986-2001</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition text-center">
    <input type="radio" name="anoConst" value="2002-2009" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">2002-2009</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition text-center">
    <input type="radio" name="anoConst" value="2010-actual" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">2010 a la actualidad</span>
    </label>
    </div>
    </div>

    <!-- Área y Pisos -->
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Área Total de Construcción (m²) <span class="text-red-500">*</span>
    </label>
    <input type="number" name="areaConstruccion" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 150" min="1" required>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Cantidad de Pisos <span class="text-red-500">*</span>
    </label>
    <input type="number" name="cantidadPisos" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 1" min="1" max="10" required>
    </div>
    </div>

    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    ¿El área de construcción por piso es igual?
    </label>
    <div class="flex space-x-6 pt-3">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="areaPisoIgual" value="si" class="radio-custom">
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="areaPisoIgual" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    ¿En qué piso se ubica el bien a asegurar?
    </label>
    <input type="number" name="pisoUbicacion" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 1" min="1">
    </div>
    </div>

    <!-- Sistema Eléctrico -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Sistema Eléctrico (seleccione todos los que apliquen)
    </label>
    <div class="grid md:grid-cols-3 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="entubado-parcial" class="checkbox-custom">
    <span class="text-sm">Entubado parcialmente</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="entubado-total" class="checkbox-custom">
    <span class="text-sm">Entubado totalmente</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="caja-breaker" class="checkbox-custom">
    <span class="text-sm">Caja de Breaker</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="cuchilla-principal" class="checkbox-custom">
    <span class="text-sm">Cuchilla principal</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="breaker-principal" class="checkbox-custom">
    <span class="text-sm">Breaker principal</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="sistemaElectrico" value="tomacorriente-polarizado" class="checkbox-custom">
    <span class="text-sm">Tomacorriente polarizado</span>
    </label>
    </div>
    </div>

    <!-- Tipo de Construcción -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Tipo de Construcción (material predominante) <span class="text-red-500">*</span>
    </label>
    <select name="tipoConstruccion" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione el tipo de construcción...</option>
    <option value="E1">E1 - Mampostería (ladrillo con concreto)</option>
    <option value="E2">E2 - Mampostería (block con concreto)</option>
    <option value="E3">E3 - Concreto reforzado colado en sitio</option>
    <option value="E4">E4 - Concreto prefabricado</option>
    <option value="E5">E5 - Panelería liviana a doble forro</option>
    <option value="E6">E6 - Panelería tipo emparedado</option>
    <option value="E7">E7 - Madera</option>
    <option value="E8">E8 - Mixto (Madera - Concreto)</option>
    <option value="E9">E9 - Marcos de concreto con muros de corte</option>
    <option value="E10">E10 - Marcos de acero</option>
    </select>
    </div>

    <!-- Estado de Conservación -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Estado de Conservación
    </label>
    <div class="grid grid-cols-3 md:grid-cols-6 gap-3">
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="optimo" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Óptimo</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="muy-bueno" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Muy bueno</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="bueno" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Bueno</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="regular" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Regular</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="malo" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Malo</span>
    </label>
    <label class="flex items-center justify-center p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="estadoConserv" value="muy-malo" class="hidden peer">
    <span class="text-sm peer-checked:font-bold">Muy malo</span>
    </label>
    </div>
    </div>

    <!-- Modificaciones Estructurales -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    ¿Se han realizado modificaciones a la estructura original para soportar cargas adicionales (SOBREPESO)? <span class="text-red-500">*</span>
    </label>
    <div class="flex space-x-6">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="modificaciones" value="si" class="radio-custom" required>
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="modificaciones" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    </div>
    </div>
    </div>

    <!-- PASO 4: Interés Asegurable y Actividad -->
    <div class="form-section" data-step="4">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-briefcase text-purple-600 mr-3"></i>Interés Asegurable
    </h2>
    <p class="text-gray-600">Relación con la propiedad y uso</p>
    </div>

    <div class="space-y-6">
    <!-- Interés Asegurable -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Interés Asegurable del Solicitante <span class="text-red-500">*</span>
    </label>
    <div class="grid md:grid-cols-3 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="interesAseg" value="propietario" class="radio-custom" required>
    <span class="text-sm">Propietario</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="interesAseg" value="arrendatario" class="radio-custom">
    <span class="text-sm">Arrendatario</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="interesAseg" value="usufructuario" class="radio-custom">
    <span class="text-sm">Usufructuario</span>
    </label>
    </div>
    </div>

    <!-- Actividad Desarrollada -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Actividad Desarrollada en el Inmueble <span class="text-red-500">*</span>
    </label>
    <select name="actividad" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="">Seleccione...</option>
    <option value="casa-habitacion">Casa de Habitación (100%)</option>
    <option value="casa-oficina">Casa de Habitación + Oficina</option>
    <option value="casa-comercio">Casa de Habitación + Comercio</option>
    <option value="otro">Otro</option>
    </select>
    </div>

    <!-- Porcentajes si es mixto -->
    <div id="porcentajes-actividad" style="display: none;">
    <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
    <h4 class="font-semibold text-gray-800 mb-3">Distribución de Actividades</h4>
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    % Dedicado a Casa de Habitación
    </label>
    <input type="number" name="porcCasa" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 70" min="0" max="100">
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    % Dedicado a Otras Ocupaciones
    </label>
    <input type="number" name="porcOtras" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 30" min="0" max="100">
    </div>
    </div>
    <div class="mt-3">
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Detalle de la Actividad
    </label>
    <textarea name="detalleActividad" rows="2" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Describa la actividad comercial o profesional"></textarea>
    </div>
    </div>
    </div>

    <!-- Inmueble Ocupado Por -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Inmueble Ocupado Por
    </label>
    <div class="flex space-x-6">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="ocupadoPor" value="propietario" class="radio-custom">
    <span class="text-sm">Propietario</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="ocupadoPor" value="inquilino" class="radio-custom">
    <span class="text-sm">Inquilino</span>
    </label>
    </div>
    </div>

    <!-- Gas LP y Sustancias -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    ¿Se utiliza Gas LP?
    </label>
    <div class="flex space-x-6">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="gasLP" value="si" class="radio-custom">
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="gasLP" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    </div>

    <!-- Colindantes -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Detalle de Colindantes
    </label>
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-xs text-gray-600 mb-1">Norte</label>
    <input type="text" name="colindanteNorte" class="input-field w-full px-4 py-2 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none text-sm" placeholder="Ej: Calle pública">
    </div>
    <div>
    <label class="block text-xs text-gray-600 mb-1">Sur</label>
    <input type="text" name="colindanteSur" class="input-field w-full px-4 py-2 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none text-sm" placeholder="Ej: Casa de habitación">
    </div>
    <div>
    <label class="block text-xs text-gray-600 mb-1">Este</label>
    <input type="text" name="colindanteEste" class="input-field w-full px-4 py-2 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none text-sm" placeholder="Ej: Terreno baldío">
    </div>
    <div>
    <label class="block text-xs text-gray-600 mb-1">Oeste</label>
    <input type="text" name="colindanteOeste" class="input-field w-full px-4 py-2 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none text-sm" placeholder="Ej: Parque">
    </div>
    </div>
    </div>

    <!-- Cercanía a Cuerpos de Agua -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    ¿La propiedad está cerca de algún cuerpo de agua?
    </label>
    <div class="grid md:grid-cols-3 gap-3 mb-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="cercaCuerpoAgua" value="rio" class="checkbox-custom">
    <span class="text-sm">Río</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="cercaCuerpoAgua" value="lago" class="checkbox-custom">
    <span class="text-sm">Lago</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="cercaCuerpoAgua" value="talud" class="checkbox-custom">
    <span class="text-sm">Talud</span>
    </label>
    </div>
    <div>
    <label class="block text-sm text-gray-600 mb-2">Distancia aproximada:</label>
    <select name="distanciaAgua" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none">
    <option value="">No aplica</option>
    <option value="0-5">0 a 5 metros</option>
    <option value="6-10">6 a 10 metros</option>
    <option value="11-20">11 a 20 metros</option>
    <option value="21-49">21 a 49 metros</option>
    <option value="50-100">50 a 100 metros</option>
    <option value="mas-100">Más de 100 metros</option>
    </select>
    </div>
    </div>
    </div>
    </div>

    <!-- PASO 5: Medidas de Seguridad -->
    <div class="form-section" data-step="5">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-shield-alt text-purple-600 mr-3"></i>Medidas de Seguridad
    </h2>
    <p class="text-gray-600">Protección y seguridad de la propiedad</p>
    </div>

    <div class="space-y-6">
    <!-- Vigilancia -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
    <h3 class="font-semibold text-gray-800 mb-3 flex items-center">
    <i class="fas fa-eye text-blue-600 mr-2"></i>Vigilancia
    </h3>
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Tipo de Vigilancia</label>
    <div class="space-y-2">
    <label class="flex items-center space-x-2">
    <input type="checkbox" name="vigilancia" value="interna" class="checkbox-custom">
    <span class="text-sm">Interna</span>
    </label>
    <label class="flex items-center space-x-2">
    <input type="checkbox" name="vigilancia" value="externa" class="checkbox-custom">
    <span class="text-sm">Externa</span>
    </label>
    </div>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Horario</label>
    <div class="space-y-2">
    <label class="flex items-center space-x-2">
    <input type="checkbox" name="horarioVigilancia" value="diurno" class="checkbox-custom">
    <span class="text-sm">Diurno</span>
    </label>
    <label class="flex items-center space-x-2">
    <input type="checkbox" name="horarioVigilancia" value="nocturno" class="checkbox-custom">
    <span class="text-sm">Nocturno</span>
    </label>
    </div>
    </div>
    </div>
    </div>

    <!-- Alarma -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    <i class="fas fa-bell text-red-600 mr-2"></i>Alarma Contra Robo
    </label>
    <div class="grid md:grid-cols-2 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="alarma" value="no-tiene" class="radio-custom">
    <span class="text-sm">No tiene</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="alarma" value="magnetica" class="radio-custom">
    <span class="text-sm">Magnética</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="alarma" value="electronica" class="radio-custom">
    <span class="text-sm">Electrónica</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="alarma" value="central-seguridad" class="radio-custom">
    <span class="text-sm">Conectada con central de seguridad</span>
    </label>
    </div>
    </div>

    <!-- Cerraduras -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    <i class="fas fa-key text-yellow-600 mr-2"></i>Cerraduras de Puertas Externas
    </label>
    <div class="grid md:grid-cols-3 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="cerraduras" value="llavin-sencillo" class="checkbox-custom">
    <span class="text-sm">Llavín sencillo</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="cerraduras" value="llavin-doble" class="checkbox-custom">
    <span class="text-sm">Llavín doble paso</span>
    </label>
    </div>
    </div>

    <!-- Tapias -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    <i class="fas fa-border-all text-gray-600 mr-2"></i>¿Tiene Tapias?
    </label>
    <div class="flex space-x-6 mb-3">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tapias" value="si" class="radio-custom">
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="tapias" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    <div id="detalles-tapias" style="display: none;">
    <div class="grid md:grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Altura (metros)</label>
    <input type="number" name="alturaTapias" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 2" step="0.1">
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">Material</label>
    <input type="text" name="materialTapias" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: Concreto">
    </div>
    <div class="md:col-span-2">
    <label class="flex items-center space-x-2">
    <input type="checkbox" name="alambreNavaja" value="si" class="checkbox-custom">
    <span class="text-sm">Con alambre navaja</span>
    </label>
    </div>
    </div>
    </div>
    </div>

    <!-- Ventanas -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    <i class="fas fa-window-maximize text-blue-600 mr-2"></i>Tipo de Ventanas
    </label>
    <div class="grid md:grid-cols-2 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="ventanas" value="frances" class="checkbox-custom">
    <span class="text-sm">Francés</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="ventanas" value="corriente" class="checkbox-custom">
    <span class="text-sm">Corriente</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="ventanas" value="celosias" class="checkbox-custom">
    <span class="text-sm">Con celosías</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="ventanas" value="verjas" class="checkbox-custom">
    <span class="text-sm">Verjas</span>
    </label>
    </div>
    </div>

    <!-- Puertas Externas -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    <i class="fas fa-door-closed text-green-600 mr-2"></i>Puertas Externas
    </label>
    <div class="grid md:grid-cols-2 gap-3">
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="puertasExternas" value="madera" class="checkbox-custom">
    <span class="text-sm">Madera</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="puertasExternas" value="vidrio" class="checkbox-custom">
    <span class="text-sm">Vidrio</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="puertasExternas" value="verjas-anteporton" class="checkbox-custom">
    <span class="text-sm">Verjas o anteportón</span>
    </label>
    <label class="flex items-center space-x-2 p-3 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="checkbox" name="puertasExternas" value="contrapuerta" class="checkbox-custom">
    <span class="text-sm">Contrapuerta</span>
    </label>
    </div>
    </div>

    <!-- Propiedad Permanece Sola -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    ¿La propiedad permanece sola durante el día?
    </label>
    <div class="flex space-x-6">
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="propiedadSola" value="si" class="radio-custom">
    <span class="text-sm">Sí</span>
    </label>
    <label class="flex items-center space-x-2 cursor-pointer">
    <input type="radio" name="propiedadSola" value="no" class="radio-custom">
    <span class="text-sm">No</span>
    </label>
    </div>
    <div id="horas-sola" style="display: none;" class="mt-3">
    <label class="block text-sm text-gray-600 mb-2">Cantidad de horas aproximadas:</label>
    <input type="number" name="horasSola" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 8" min="0" max="24">
    </div>
    </div>

    <!-- Otras Medidas de Seguridad -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Otras medidas de seguridad (opcional)
    </label>
    <textarea name="otrasMedidasSeguridad" rows="3" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Describa cualquier otra medida de seguridad no mencionada anteriormente..."></textarea>
    </div>
    </div>
    </div>

    <!-- PASO 6: Coberturas y Rubros -->
    <div class="form-section" data-step="6">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-umbrella text-purple-600 mr-3"></i>Coberturas y Montos
    </h2>
    <p class="text-gray-600">Seleccione las coberturas y montos a asegurar</p>
    </div>

    <div class="space-y-6">
    <!-- Coberturas Básicas -->
    <div class="bg-purple-50 border-2 border-purple-200 rounded-lg p-6">
    <h3 class="text-xl font-bold text-gray-800 mb-4">Coberturas Básicas</h3>
    
    <!-- Cobertura V -->
    <div class="mb-4">
    <label class="flex items-start space-x-3 cursor-pointer">
    <input type="checkbox" name="coberturaV" value="si" class="checkbox-custom mt-1" checked>
    <div>
    <div class="font-semibold text-gray-800">V: Daño Directo Bienes Inmuebles</div>
    <div class="text-sm text-gray-600">Protege la estructura de tu vivienda contra incendios, terremotos, inundaciones y más</div>
    </div>
    </label>
    </div>

    <!-- Cobertura X o Y -->
    <div class="space-y-3">
    <label class="flex items-start space-x-3 cursor-pointer p-4 border-2 border-gray-200 rounded-lg hover:border-purple-500 transition">
    <input type="radio" name="coberturaContenido" value="Y" class="radio-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">Y: Daño Directo de Contenidos (ampara robo)</div>
    <div class="text-sm text-gray-600">Protege tus pertenencias incluyendo cobertura contra robo</div>
    </div>
    </label>
    <label class="flex items-start space-x-3 cursor-pointer p-4 border-2 border-gray-200 rounded-lg hover:border-purple-500 transition">
    <input type="radio" name="coberturaContenido" value="X" class="radio-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">X: Daño Directo de Contenidos (excluye robo)</div>
    <div class="text-sm text-gray-600">Protege tus pertenencias sin incluir cobertura contra robo</div>
    </div>
    </label>
    </div>
    </div>

    <!-- Coberturas Adicionales -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-6">
    <h3 class="text-xl font-bold text-gray-800 mb-4">Coberturas Adicionales (Opcionales)</h3>
    
    <div class="space-y-3">
    <label class="flex items-start space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-blue-500 transition">
    <input type="checkbox" name="coberturaD" value="si" class="checkbox-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">D: Convulsiones de la Naturaleza</div>
    <div class="text-sm text-gray-600">Protección adicional contra desastres naturales</div>
    </div>
    </label>

    <label class="flex items-start space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-blue-500 transition">
    <input type="checkbox" name="coberturaK" value="si" class="checkbox-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">K: Responsabilidad Civil</div>
    <div class="text-sm text-gray-600">Cobertura por daños a terceros</div>
    </div>
    </label>

    <label class="flex items-start space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-blue-500 transition">
    <input type="checkbox" name="coberturaP" value="si" class="checkbox-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">P: Accidentes Personales</div>
    <div class="text-sm text-gray-600">Protección para el asegurado y su familia</div>
    </div>
    </label>
    </div>
    </div>

    <!-- Montos a Asegurar -->
    <div class="bg-green-50 border border-green-200 rounded-lg p-6">
    <h3 class="text-xl font-bold text-gray-800 mb-4">Montos a Asegurar</h3>
    
    <div class="space-y-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Residencia (Edificio) <span class="text-red-500">*</span>
    </label>
    <div class="relative">
    <span class="absolute left-4 top-3 text-gray-500">₡</span>
    <input type="number" name="montoResidencia" class="input-field w-full pl-10 pr-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 50000" min="0" required>
    </div>
    <p class="text-xs text-gray-500 mt-1">Valor de la construcción de tu vivienda</p>
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Propiedad Personal (Contenido)
    </label>
    <div class="relative">
    <span class="absolute left-4 top-3 text-gray-500">₡</span>
    <input type="number" name="montoContenido" class="input-field w-full pl-10 pr-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 150000" min="0">
    </div>
    <p class="text-xs text-gray-500 mt-1">Valor de muebles, electrodomésticos, ropa, etc.</p>
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Joyería (opcional)
    </label>
    <div class="relative">
    <span class="absolute left-4 top-3 text-gray-500">₡</span>
    <input type="number" name="montoJoyeria" class="input-field w-full pl-10 pr-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 20000" min="0">
    </div>
    </div>

    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Obras de Arte (opcional)
    </label>
    <div class="relative">
    <span class="absolute left-4 top-3 text-gray-500">₡</span>
    <input type="number" name="montoObrasArte" class="input-field w-full pl-10 pr-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" placeholder="Ej: 30000" min="0">
    </div>
    </div>
    </div>
    </div>

    <!-- Moneda y Vigencia -->
    <div class="grid md:grid-cols-2 gap-4">
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Moneda <span class="text-red-500">*</span>
    </label>
    <select name="moneda" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="colones">Colones (₡)</option>
    <option value="dolares">Dólares ($)</option>
    </select>
    </div>
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-2">
    Plan de Pago <span class="text-red-500">*</span>
    </label>
    <select name="planPago" class="input-field w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-purple-500 focus:outline-none" required>
    <option value="anual">Anual</option>
    <option value="semestral">Semestral</option>
    <option value="trimestral">Trimestral</option>
    <option value="mensual">Mensual</option>
    </select>
    </div>
    </div>

    <!-- Opción de Aseguramiento -->
    <div>
    <label class="block text-sm font-semibold text-gray-700 mb-3">
    Opción de Aseguramiento <span class="text-red-500">*</span>
    </label>
    <div class="grid md:grid-cols-2 gap-4">
    <label class="flex items-start space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="opcionAseguramiento" value="100" class="radio-custom mt-1" required>
    <div>
    <div class="font-semibold text-gray-800">Al 100%</div>
    <div class="text-sm text-gray-600">Cobertura completa del valor asegurado</div>
    </div>
    </label>
    <label class="flex items-start space-x-3 p-4 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-purple-500 transition">
    <input type="radio" name="opcionAseguramiento" value="coaseguro-80" class="radio-custom mt-1">
    <div>
    <div class="font-semibold text-gray-800">Coaseguro 80%</div>
    <div class="text-sm text-gray-600">Opción económica con participación en pérdidas</div>
    </div>
    </label>
    </div>
    </div>
    </div>
    </div>

    <!-- PASO 7: Resumen y Confirmación -->
    <div class="form-section" data-step="7">
    <div class="mb-8">
    <h2 class="text-3xl font-bold text-gray-800 mb-2">
    <i class="fas fa-check-circle text-green-600 mr-3"></i>Resumen de Solicitud
    </h2>
    <p class="text-gray-600">Revisa tu información antes de enviar</p>
    </div>

    <div id="resumen-contenido" class="space-y-6">
    <!-- El resumen se generará dinámicamente con JavaScript -->
    </div>

    <div class="flex justify-end space-x-3 mt-4">
    <button id="resumen-print" type="button" class="px-4 py-2 bg-gray-100 rounded-md text-sm hover:bg-gray-200">
    <i class="fas fa-print mr-2"></i>Imprimir
    </button>
    </div>

    <!-- Consentimientos -->
    <div class="mt-8 space-y-4">
    <div class="bg-yellow-50 border border-yellow-300 rounded-lg p-4">
    <label class="flex items-start space-x-3 cursor-pointer">
    <input type="checkbox" name="consentimientoInfo" class="checkbox-custom mt-1" required>
    <div class="text-sm text-gray-700">
    <strong>Declaro que la información detallada en este documento es verídica.</strong> En caso de comprobarse cualquier omisión o falsa declaración, eximo al Instituto Nacional de Seguros de cualquier responsabilidad, dando como resultado la terminación del contrato de seguros.
    </div>
    </label>
    </div>

    <div class="bg-blue-50 border border-blue-300 rounded-lg p-4">
    <label class="flex items-start space-x-3 cursor-pointer">
    <input type="checkbox" name="consentimientoGrabacion" class="checkbox-custom mt-1" required>
    <div class="text-sm text-gray-700">
    <strong>Consiento expresamente</strong> que el Instituto Nacional de Seguros grabe y utilice las llamadas telefónicas que se realicen a las líneas de servicio, como prueba para los procesos administrativos y judiciales.
    </div>
    </label>
    </div>

    <div class="bg-green-50 border border-green-300 rounded-lg p-4">
    <label class="flex items-start space-x-3 cursor-pointer">
    <input type="checkbox" name="consentimientoDatos" class="checkbox-custom mt-1" required>
    <div class="text-sm text-gray-700">
    <strong>Autorizo al INS</strong> a incluir mi información en una base de datos bajo su responsabilidad, con medidas de seguridad adecuadas, para ejecutar el contrato y ofrecer productos o servicios adicionales.
    </div>
    </label>
    </div>
    </div>
    </div>

    <!-- Botones de Navegación -->
    <div class="flex justify-between items-center mt-8 pt-6 border-t-2 border-gray-200">
    <button type="button" id="btn-prev" class="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition flex items-center" style="display: none;">
    <i class="fas fa-arrow-left mr-2"></i>Anterior
    </button>
    <div></div>
    <button type="button" id="btn-next" class="px-8 py-3 gradient-bg text-white rounded-lg font-semibold hover:opacity-90 transition flex items-center">
    Siguiente<i class="fas fa-arrow-right ml-2"></i>
    </button>
    <button type="submit" id="btn-submit" class="px-8 py-3 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition flex items-center" style="display: none;">
    <i class="fas fa-paper-plane mr-2"></i>Enviar Solicitud
    </button>
    </div>
    </form>
    </div>

    <!-- Modal de Confirmación -->
    <div id="modal-confirmacion" class="fixed inset-0 bg-black bg-opacity-50 hidden flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded-2xl max-w-md w-full p-8 text-center animate-fadeIn">
    <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
    <i class="fas fa-check text-green-600 text-4xl"></i>
    </div>
    <h3 class="text-2xl font-bold text-gray-800 mb-4">¡Solicitud Enviada!</h3>
    <p class="text-gray-600 mb-6">
    Hemos recibido tu solicitud de seguro. Un agente se pondrá en contacto contigo en las próximas 24 horas.
    </p>
    <p class="text-sm text-gray-500 mb-6">
    Recibirás un correo electrónico con el número de referencia de tu solicitud.
    </p>
    <a href="/index.php" class="inline-block px-8 py-3 gradient-bg text-white rounded-lg font-semibold hover:opacity-90 transition">
    Volver al Inicio
    </a>
    </div>
    </div>

    <!-- Geo-module: carga cr-provincias.json y puebla selects -->
    <script>
    (async function(){
      function normalizeKey(s){
        if(!s && s!==0) return '';
        try{
          return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g,'');
        }catch(e){
          return String(s).toLowerCase().replace(/\s+/g,'');
        }
      }

      try{
        const url = '/assets/data/cr-provincias.json?v=1';
        console.debug('[Geo] cargando JSON desde', url);
        const resp = await fetch(url, {cache: 'no-store'});
        if(!resp.ok){ console.error('[Geo] fallo cargando cr-provincias.json:', resp.status, resp.statusText); return; }
        const GEO = await resp.json();
        console.debug('[Geo] JSON cargado. provincias:', Object.keys(GEO).slice(0,20));

        const normMap = {};
        Object.keys(GEO).forEach(k => { normMap[normalizeKey(k)] = k; });

        function findProvKey(rawProv){
          if(!rawProv) return null;
          const n = normalizeKey(rawProv);
          if(normMap[n]) return normMap[n];
          for(const nk of Object.keys(normMap)){
            if(nk.includes(n) || n.includes(nk)) return normMap[nk];
          }
          return null;
        }

        function populateCantones(provValue, cantonSel, distritoSel, restoreSelected){
          cantonSel.innerHTML = '<option value="">Seleccione...</option>';
          distritoSel.innerHTML = '<option value="">Seleccione...</option>';
          if(!provValue) return;
          const matchedKey = findProvKey(provValue);
          if(!matchedKey){
            console.warn('[Geo] No se encontró provincia en JSON para:', provValue);
            return;
          }
          const cantonesObj = GEO[matchedKey];
          Object.keys(cantonesObj).forEach(c => {
            const opt = document.createElement('option'); opt.value = c; opt.textContent = c; cantonSel.appendChild(opt);
          });
          if(restoreSelected && cantonSel.dataset.restoreValue){
            cantonSel.value = cantonSel.dataset.restoreValue;
            fillDistritos(cantonSel, distritoSel, true);
          }
        }

        function fillDistritos(cantonSel, distritoSel, restoreSelected){
          const provSel = document.querySelector(`[name="${cantonSel.dataset.provName}"]`);
          const provVal = provSel ? provSel.value : null;
          distritoSel.innerHTML = '<option value="">Seleccione...</option>';
          if(!provVal) return;
          const matchedProvKey = findProvKey(provVal);
          if(!matchedProvKey) return;
          const lista = (GEO[matchedProvKey] && GEO[matchedProvKey][cantonSel.value]) || [];
          if(!lista || lista.length===0){
            const normalizedCanton = normalizeKey(cantonSel.value || '');
            const possible = Object.keys(GEO[matchedProvKey]).find(k => normalizeKey(k) === normalizedCanton);
            if(possible){
              (GEO[matchedProvKey][possible] || []).forEach(d=>{
                const opt = document.createElement('option'); opt.value = d; opt.textContent = d; distritoSel.appendChild(opt);
              });
            } else {
              console.warn('[Geo] No se hallaron distritos para canton:', cantonSel.value, 'en provincia', matchedProvKey);
            }
            if(restoreSelected && distritoSel.dataset.restoreValue) distritoSel.value = distritoSel.dataset.restoreValue;
            return;
          }
          lista.forEach(d=>{
            const opt = document.createElement('option'); opt.value = d; opt.textContent = d; distritoSel.appendChild(opt);
          });
          if(restoreSelected && distritoSel.dataset.restoreValue) distritoSel.value = distritoSel.dataset.restoreValue;
        }

        function setupPair(provName, cantonId, distritoId){
          const provSel = document.querySelector(`[name="${provName}"]`);
          const cantonSel = document.getElementById(cantonId);
          const distritoSel = document.getElementById(distritoId);
          if(!provSel || !cantonSel || !distritoSel) return;
          cantonSel.dataset.provName = provName;
          if(cantonSel.value) cantonSel.dataset.restoreValue = cantonSel.value;
          if(distritoSel.value) distritoSel.dataset.restoreValue = distritoSel.value;

          provSel.addEventListener('change', function(){
            populateCantones(this.value, cantonSel, distritoSel, false);
            cantonSel.value = '';
            distritoSel.value = '';
          });

          cantonSel.addEventListener('change', function(){
            fillDistritos(cantonSel, distritoSel, false);
          });

          if(provSel.value){
            populateCantones(provSel.value, cantonSel, distritoSel, true);
          }
        }

        setupPair('provincia','canton','distrito');
        setupPair('provinciaProp','cantonProp','distritoProp');

        console.debug('[Geo] inicializado correctamente');
      }catch(err){
        console.error('[Geo] error general:', err);
      }
    })();
    </script>

    <!-- Lógica principal (tu script existente) -->
    <script src="/assets/js/form-logic.js?v=2025-11-07"></script>

    <!-- Generador de resumen (mantengo la lógica que ya tenías) -->
    <script>
    /* (El script del resumen queda igual; mapea los campos que agregamos) */
    const fieldLabels = {
      tipoId: 'Tipo de Identificación',
      numeroId: 'Número de Identificación',
      nombreCompleto: 'Nombre Completo',
      provincia: 'Provincia',
      canton: 'Cantón',
      distrito: 'Distrito',
      pais: 'País',
      direccion: 'Dirección',
      telefonoCelular: 'Teléfono Celular',
      telefonoDomicilio: 'Teléfono Domicilio',
      telefonoOficina: 'Teléfono Oficina',
      correo: 'Correo Electrónico',

      tipoPropiedad: 'Tipo de Propiedad',
      latitud: 'Latitud',
      longitud: 'Longitud',
      provinciaProp: 'Provincia (Propiedad)',
      cantonProp: 'Cantón (Propiedad)',
      distritoProp: 'Distrito (Propiedad)',
      esquina: 'Localizado en esquina',
      urbanizacion: 'Urbanización / Barrio',
      otrasSenas: 'Otras señas',
      folioReal: 'Folio Real / Finca',

      anoConst: 'Año de Construcción',
      areaConstruccion: 'Área Construcción (m²)',
      cantidadPisos: 'Cantidad de Pisos',
      areaPisoIgual: 'Área por piso igual',
      pisoUbicacion: 'Piso de Ubicación',
      sistemaElectrico: 'Sistema Eléctrico',
      tipoConstruccion: 'Tipo de Construcción',
      estadoConserv: 'Estado de Conservación',
      modificaciones: 'Modificaciones estructurales',

      interesAseg: 'Interés Asegurable',
      actividad: 'Actividad en Inmueble',
      porcCasa: '% Casa',
      porcOtras: '% Otras',
      detalleActividad: 'Detalle de la Actividad',
      ocupadoPor: 'Inmueble ocupado por',
      gasLP: 'Uso de Gas LP',

      vigilancia: 'Vigilancia',
      horarioVigilancia: 'Horario Vigilancia',
      alarma: 'Alarma',
      cerraduras: 'Cerraduras',
      tapias: 'Tapias',
      alturaTapias: 'Altura Tapias (m)',
      materialTapias: 'Material Tapias',
      alambreNavaja: 'Alambre Navaja',
      ventanas: 'Tipo de Ventanas',
      puertasExternas: 'Puertas Externas',
      propiedadSola: 'Propiedad permanece sola',
      horasSola: 'Horas aproximadas sola',
      otrasMedidasSeguridad: 'Otras medidas de seguridad',

      coberturaV: 'Cobertura V (Edificio)',
      coberturaContenido: 'Cobertura Contenidos',
      coberturaD: 'Cobertura D (Desastres)',
      coberturaK: 'Cobertura K (Resp. Civil)',
      coberturaP: 'Cobertura P (Accidentes)',
      montoResidencia: 'Monto Residencia',
      montoContenido: 'Monto Contenido',
      montoJoyeria: 'Monto Joyería',
      montoObrasArte: 'Monto Obras de Arte',
      moneda: 'Moneda',
      planPago: 'Plan de Pago',
      opcionAseguramiento: 'Opción de Aseguramiento',

      consentimientoInfo: 'Consentimiento: Información verídica',
      consentimientoGrabacion: 'Consentimiento: Grabación',
      consentimientoDatos: 'Consentimiento: Tratamiento de Datos'
    };

    function readFieldValue(form, name) {
      const els = Array.from(form.querySelectorAll(`[name="${name}"]`));
      if (!els.length) return null;
      if (els.length === 1) {
        const el = els[0];
        if (el.type === 'checkbox') return el.checked ? (el.value || 'Sí') : null;
        if (el.type === 'radio') {
          const checked = form.querySelector(`[name="${name}"]:checked`);
          return checked ? checked.value : null;
        }
        return el.value ? el.value : null;
      }
      const checked = els.filter(e => (e.type === 'checkbox' && e.checked) || (e.type === 'radio' && e.checked));
      if (checked.length === 0) return null;
      const values = checked.map(e => e.value || 'Sí');
      return values.join(', ');
    }

    function formatCurrency(value, moneda) {
      if (!value) return '';
      const num = Number(value);
      if (isNaN(num)) return value;
      if (!moneda || moneda === 'colones') {
        try { return new Intl.NumberFormat('es-CR', { style: 'currency', currency: 'CRC', maximumFractionDigits: 0 }).format(num); } catch(e) { return '₡ ' + Math.round(num).toLocaleString(); }
      } else {
        try { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(num); } catch(e) { return '$ ' + Number(num).toFixed(2); }
      }
    }

    function buildSectionHTML(title, rows) {
      const rowsHtml = rows.map(r => {
        const safeValue = r.value ? String(r.value) : '<span class="text-gray-400">No indicado</span>';
        return `
        <div class="grid grid-cols-3 gap-x-4 py-2 border-b last:border-b-0">
          <div class="col-span-1 text-sm text-gray-600">${r.label}</div>
          <div class="col-span-2 text-sm text-gray-800">${safeValue}</div>
        </div>
        `;
      }).join('');
      return `
      <div class="bg-white shadow-sm rounded-lg border p-4">
        <div class="flex items-center justify-between mb-3">
          <h4 class="text-md font-semibold text-gray-800">${title}</h4>
        </div>
        <div class="border-t -mx-4 px-4">${rowsHtml}</div>
      </div>
      `;
    }

    function generateSummary() {
      const form = document.getElementById('insurance-form');
      const container = document.getElementById('resumen-contenido');
      if (!form || !container) return;

      const monedaVal = readFieldValue(form, 'moneda');

      const personalKeys = ['tipoId','numeroId','nombreCompleto','provincia','canton','distrito','pais','direccion','telefonoCelular','telefonoDomicilio','telefonoOficina','correo'];
      const propertyKeys = ['tipoPropiedad','latitud','longitud','provinciaProp','cantonProp','distritoProp','esquina','urbanizacion','otrasSenas','folioReal'];
      const construccionKeys = ['anoConst','areaConstruccion','cantidadPisos','areaPisoIgual','pisoUbicacion','sistemaElectrico','tipoConstruccion','estadoConserv','modificaciones'];
      const seguridadKeys = ['vigilancia','horarioVigilancia','alarma','cerraduras','tapias','alturaTapias','materialTapias','alambreNavaja','ventanas','puertasExternas','propiedadSola','horasSola','otrasMedidasSeguridad'];

      const personal = personalKeys.map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));
      const propiedad = propertyKeys.map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));
      const construccion = construccionKeys.map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));
      const seguridad = seguridadKeys.map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));

      const coberturasList = ['coberturaV','coberturaContenido','coberturaD','coberturaK','coberturaP'].map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));
      const montos = [
        { key: 'montoResidencia', currency: true },
        { key: 'montoContenido', currency: true },
        { key: 'montoJoyeria', currency: true },
        { key: 'montoObrasArte', currency: true }
      ].map(item => {
        const raw = readFieldValue(form, item.key);
        return { label: fieldLabels[item.key] || item.key, value: item.currency ? formatCurrency(raw, monedaVal) : raw };
      });

      const otrosCoberturas = ['moneda','planPago','opcionAseguramiento'].map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) }));
      const consentimientos = ['consentimientoInfo','consentimientoGrabacion','consentimientoDatos'].map(k => ({ label: fieldLabels[k] || k, value: readFieldValue(form,k) ? 'Aceptado' : 'No aceptado' }));

      const sections = [
        { title: 'Datos Personales', rows: personal, step: 1 },
        { title: 'Datos de la Propiedad', rows: propiedad, step: 2 },
        { title: 'Características de Construcción', rows: construccion, step: 3 },
        { title: 'Medidas de Seguridad', rows: seguridad, step: 5 },
        { title: 'Coberturas (seleccionadas)', rows: coberturasList.concat(montos).concat(otrosCoberturas), step: 6 },
        { title: 'Consentimientos', rows: consentimientos, step: 7 }
      ];

      container.innerHTML = sections.map(s => buildSectionHTML(s.title, s.rows)).join('');
    }

    document.addEventListener('DOMContentLoaded', function () {
      const btnNext = document.getElementById('btn-next');
      const btnPrev = document.getElementById('btn-prev');

      function maybeGenerate() {
        const paso7 = document.querySelector('.form-section[data-step="7"].active');
        if (paso7) generateSummary();
      }

      if (btnNext) btnNext.addEventListener('click', () => setTimeout(maybeGenerate, 150));
      if (btnPrev) btnPrev.addEventListener('click', () => setTimeout(maybeGenerate, 150));

      document.addEventListener('stepChanged', maybeGenerate);

      maybeGenerate();

      const btnPrint = document.getElementById('resumen-print');
      if (btnPrint) btnPrint.addEventListener('click', () => window.print());
    });
    </script>

    <!-- Footer -->
    <footer class="bg-gray-900 text-white py-6 mt-12">
        <div class="container mx-auto px-4 text-center text-gray-400 text-sm">
            <p>&copy; 2025 - AGENTE INS AUTORIZADO: 110886. Todos los derechos reservados.</p>
            <div class="mt-3 space-x-4">
                <a href="/privacidad.php" class="hover:text-white transition">Política de Privacidad</a>
                <span>|</span>
                <a href="/terminos.php" class="hover:text-white transition">Términos y Condiciones</a>
            </div>
        </div>
    </footer>

</body>
</html>